server:
  port: 8082

spring:
  application:
    name: vul-fixed
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

logging:
  level:
    com.devsec.vulfixed: DEBUG
    org.springframework.web: INFO
