server:
  port: 8081

spring:
  application:
    name: vul-verify
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:vuldb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.devsec.vulnerability.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.devsec.vulnerability: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
